<?php
/**
 * linker_generator.php
 *
 * Generates client/src/js/linker.js
 * - Imports ALL JS modules under client/src/js
 * - Links all exports onto globalThis
 * - Warns on name collisions (including browser globals)
 */

$jsDir = realpath(__DIR__ . '/../../../../client/src/js');
$outFile = $jsDir . '/linker.js';
$excluded = ['linker.js', 'main.js'];

if (!$jsDir || !is_dir($jsDir)) {
    die("JS directory not found: $jsDir\n");
}

$modules = [];
$counter = 0;

$it = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($jsDir, RecursiveDirectoryIterator::SKIP_DOTS)
);

foreach ($it as $file) {
    if (!$file->isFile()) continue;
    if ($file->getFilename() === 'linker.js') continue;
    if (!str_ends_with($file->getFilename(), '.js')) continue;
    if (in_array($file->getFilename(), $excluded, true)) continue;

    $abs = str_replace('\\', '/', $file->getPathname());
    $rel = substr($abs, strlen($jsDir) + 1);

    $modules[] = [
        'var'  => 'm' . str_pad((string)$counter++, 4, '0', STR_PAD_LEFT),
        'path' => './' . $rel
    ];
}

$out  = "/* AUTO-GENERATED by linker_generator.php\n";
$out .= " * DO NOT EDIT MANUALLY.\n";
$out .= " */\n\n";

// Imports
foreach ($modules as $m) {
    $out .= "import * as {$m['var']} from \"{$m['path']}\";\n";
}

$out .= "\n";
$out .= "globalThis.__linker_sources ??= Object.create(null);\n\n";
$out .= "function __link(module, source) {\n";
$out .= "    for (const k in module) {\n";
$out .= "        const val = module[k];\n";
$out .= "        if (k in globalThis) {\n";
$out .= "            const prev = globalThis.__linker_sources[k] ?? \"<preexisting global>\";\n";
$out .= "            if (globalThis[k] !== val) {\n";
$out .= "                console.warn(\"Linker duplicate:\", k, { prev, next: source });\n";
$out .= "            }\n";
$out .= "            continue;\n";
$out .= "        }\n";
$out .= "        globalThis[k] = val;\n";
$out .= "        globalThis.__linker_sources[k] = source;\n";
$out .= "    }\n";
$out .= "}\n\n";

// Link calls
foreach ($modules as $m) {
    $out .= "__link({$m['var']}, \"{$m['path']}\");\n";
}

file_put_contents($outFile, $out);

echo "Generated linker.js with " . count($modules) . " modules\n";
